### PR TITLE
Added intitial table creation SQL and updated relational mapping

### PR DESCRIPTION
**Pull request by abe16s**
Added PAYMENT_HISTORY view that combines MEMBER_TABLE & RECEIPT tables and selects ID, Reason & Receipt_No attributes

### CODE REVIEW

**Comment by beka-birhanu** [comment]
you didint update the relational mapping you added another file

**Comment by beka-birhanu** [comment]
and what about the thing i told you to prohbit delation of entity

**Comment by abe16s** [comment]
> you didint update the relational mapping you added another file

I know, it's because the have different names, the old one will be deleted

**Comment by abe16s** [comment]
> and what about the thing i told you to prohbit delation of entity

I added it, see it at the end of the sql file

**Comment by beka-birhanu** [comment]
then what is the need for set null on delete

**Comment by abe16s** [comment]
> then what is the need for set null on delete

it doesn't hurt anything
yiqr?

**Comment by beka-birhanu** [comment]
it doesnt have a use either

**Comment by abe16s** [comment]
> it doesnt have a use either

okay any other before I commit again

**Comment by beka-birhanu** [comment]
that is the only change happend  right?

**Comment by beka-birhanu** [comment]
i will merge it latter but first lemme check it bedenb. i am on other thing right now

**Comment by abe16s** [comment]
changed the type of Receipt_No attribut to INT, it was varchar before

**Pull request merged**
