### PR TITLE
Members branch

### PR DESCRIPTION
**Pull request by abe16s**

### CODE REVIEW

**Comment by beka-birhanu** [comment]
yeah merge it

**Comment by beka-birhanu** [comment]
wait there is some thing

**Comment by abe16s** [comment]
What?

**Comment by beka-birhanu** [comment]
in individual member the panels under the family memebers are clickable

**Comment by abe16s** [comment]
No why would they be
They're just information eko

**Comment by beka-birhanu** [comment]
thats what i am saying

**Pull request merged**
